### ISSUE TITLE
Register Package

### ISSUE THREAD

**Issue by mcmcgrath13** [bcbi/REDCap.jl#4]
Make package public and register with julia

**Comment by FLCN17** [comment]
Working on it- Waiting for Travis and JuliaCI to pass/allow us through

**Comment by FLCN17** [comment]
Currently waiting for approval- issue with the JuliaCI running tests (which will fail) and failing.

**Comment by DilumAluthge** [comment]
This is done: [https://github.com/JuliaRegistries/General/tree/master/R/REDCap](https://github.com/JuliaRegistries/General/tree/master/R/REDCap)
